$(function(){
	//启用弹出层
	$('.modal').modal();
	//输入数据，riftimg是地图显示，contentimg是弹出层显示
	var json =[{
		"name":"theshy",
		"title":"The Shy领域",
	    "txt":"传说中的LPL上单Boss——The Shy在此出没，强行收过路费无数",
	    "riftimg":"images/theshy.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"150px",
	    "top":"90px",
	    "left":"180px"
	    },{
	    "name":"seven",
		"title":"7777777",
	    "txt":"你个小X崽子又在暗示我",
	    "riftimg":"images/777777.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"80px",
	    "top":"550px",
	    "left":"860px"
	    },{
	    "name":"mouse",
		"title":"专业开车",
	    "txt":"追光者",
	    "riftimg":"images/mousetexi.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"260px",
	    "top":"240px",
	    "left":"320px"
	    },{
	    "name":"condi",
		"title":"condi",
	    "txt":"龙！是！我！的！",
	    "riftimg":"images/condi.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"100px",
	    "top":"180px",
	    "left":"360px"
	    },{
	    "name":"deft",
		"title":"朝鲜飞行员",
	    "txt":"每个人都会打飞机，这对飞机来说很不公平",
	    "riftimg":"images/deft.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"110px",
	    "top":"300px",
	    "left":"450px"
	    },{
	    "name":"7777777",
		"title":"明凯",
	    "txt":"明凯不做暗事",
	    "riftimg":"images/7plus.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"100px",
	    "top":"160px",
	    "left":"320px"
	    },{
	    "name":"allstars",
		"title":"球赛",
	    "txt":"九个盲僧一个球",
	    "riftimg":"images/qiuqiu.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"90px",
	    "top":"220px",
	    "left":"620px"
	    },{
	    "name":"worldcenter",
		"title":"世界聚焦于你",
	    "txt":"7777777永不团灭",
	    "riftimg":"images/worldcenter.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"50px",
	    "top":"400px",
	    "left":"510px"
	    },{
	    "name":"Level4",
		"title":"Level4",
	    "txt":"你怕了吗？",
	    "riftimg":"images/Lv.4.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"35px",
	    "top":"490px",
	    "left":"478px"
	    },{
	    "name":"RyuAndFaker",
		"title":"RyuAndFaker",
	    "txt":"传奇由此生",
	    "riftimg":"images/RyuAndFaker.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"110px",
	    "top":"465px",
	    "left":"307px"
	    },{
	    "name":"Godv",
		"title":"Godv",
	    "txt":"皮",
	    "riftimg":"images/Godv.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"110px",
	    "top":"655px",
	    "left":"290px"
	    },{
	    "name":"pray",
		"title":"pray",
	    "txt":"皮",
	    "riftimg":"images/pray.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"90px",
	    "top":"540px",
	    "left":"230px"
	    },{
	    "name":"UZI",
		"title":"UZI",
	    "txt":"皮",
	    "riftimg":"images/UZI.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"90px",
	    "top":"255px",
	    "left":"240px"
	    },{
	    "name":"X4",
		"title":"X4",
	    "txt":"皮",
	    "riftimg":"images/X4.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"60px",
	    "top":"230px",
	    "left":"160px"
	    },{
	    "name":"AJhere",
		"title":"AJhere",
	    "txt":"皮",
	    "riftimg":"images/AJhere.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"60px",
	    "top":"315px",
	    "left":"160px"
	    },{
	    "name":"Korol",
		"title":"Korol反杀圈",
	    "txt":"皮",
	    "riftimg":"images/Korol.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"80px",
	    "top":"55px",
	    "left":"333px"
	    },{
	    "name":"NoBanMetal",
		"title":"为什么不Ban铁男",
	    "txt":"皮",
	    "riftimg":"images/NoBanMetal.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"100px",
	    "top":"175px",
	    "left":"590px"
	    },{
	    "name":"doublelift",
		"title":"oublelit",
	    "txt":"没有DF",
	    "riftimg":"images/doublelift.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"60px",
	    "top":"205px",
	    "left":"836px"
	    },{
	    "name":"Hai",
		"title":"Hai掌门",
	    "txt":"没有DF",
	    "riftimg":"images/Hai.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"40px",
	    "top":"326px",
	    "left":"880px"
	    },{
	    "name":"piglet",
		"title":"这个笑容由你来守护",
	    "txt":"没有DF",
	    "riftimg":"images/piglet.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"80px",
	    "top":"620px",
	    "left":"660px"
	    },{
	    "name":"Levi",
		"title":"大魔法师的手速",
	    "txt":"没有DF",
	    "riftimg":"images/Levi.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"100px",
	    "top":"490px",
	    "left":"600px"
	    },{
	    "name":"SevenAndHecarim",
		"title":"哦，这就是7~",
	    "txt":"爱的深沉",
	    "riftimg":"images/7AndHecarim.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"130px",
	    "top":"420px",
	    "left":"520px"
	    },{
	    "name":"Faker",
		"title":"强者恒强",
	    "txt":"爱的深沉",
	    "riftimg":"images/FakerShockWave.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"80px",
	    "top":"350px",
	    "left":"540px"
	    },{
	    "name":"Stanley",
		"title":"Stanley的豹女活动范围",
	    "txt":"爱的深沉",
	    "riftimg":"images/Stanley.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"130px",
	    "top":"90px",
	    "left":"430px"
	    },{
	    "name":"DeftPentaKill",
		"title":"Deft五杀地",
	    "txt":"爱的深沉",
	    "riftimg":"images/DeftPentaKill.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"90px",
	    "top":"240px",
	    "left":"300px"
	    },{
	    "name":"Smeb",
		"title":"天雷",
	    "txt":"爱的深沉",
	    "riftimg":"images/Smeb.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"40px",
	    "top":"410px",
	    "left":"460px"
	    },{
	    "name":"Pawn",
		"title":"地火",
	    "txt":"爱的深沉",
	    "riftimg":"images/Pawn.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"60px",
	    "top":"460px",
	    "left":"660px"
	    },{
	    "name":"SevenAndUZI",
		"title":"2级抓下",
	    "txt":"爱的深沉",
	    "riftimg":"images/SevenAndUZI.png",
	    "contentimg":"images/theshycontent.jpg",
	    "video":"",
	    "width":"80px",
	    "top":"650px",
	    "left":"750px"
	    }
	    ];
	//显示joke
	function WarNeverChange(){
		$(json).map(function(index,item){
			var t = this;
			//召唤师峡谷地图显示
			t.box = $("<a class='"+item.name+" modal-trigger' href='#modalmsg'></a>").appendTo($(".rift"));
			t.img = $("<img src='"+item.riftimg+"' class='itemimg' alt='"+item.name+"' ctitle='"+item.title+"' cimg='"+item.contentimg+"' ctxt='"+item.txt+"' cvedio='"+item.video+"'/>").appendTo($(t.box));
			$(t.img).css({
				"width" :item.width,
				"position":"absolute",
				"top":item.top,
				"left":item.left
			});
		});	
	}
	WarNeverChange();
	//modals
	$(".itemimg").click(function(e){
		$("#modalmsg").html("");
		var content = $("<div class='modal-content'></div").appendTo($("#modalmsg"));
		var footer = $("<div class='modal-footer'></div>").appendTo($("#modalmsg"));
		$("<h4>"+$(this).attr("ctitle")+"</h4>").appendTo($(content));
		$("<p>"+$(this).attr("ctxt")+"</p>").appendTo($(content));
		$("<img class='' src='"+$(this).attr("cimg")+"' alt='"+$(this).attr("alt")+"img' />").appendTo($(content));
		$("<a class='btn-floating waves-effect waves-light red'><i class='material-icons'>movie</i></a>").appendTo($('.modal-footer'));
	});

	
});
